"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { MapPin, Pencil, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Address = {id:string;label:string;recipient?:string|null;postalCode:string;street:string;number:string;complement?:string|null;district:string;city:string;state:string;isDefault:boolean};
const empty={label:"Casa",recipient:"",postalCode:"",street:"",number:"",complement:"",district:"",city:"",state:"SP",isDefault:false};
export function AddressManager({addresses}:{addresses:Address[]}){const router=useRouter();const[editing,setEditing]=useState<Address|typeof empty|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const payload={label:fd.get("label"),recipient:fd.get("recipient")||null,postalCode:fd.get("postalCode"),street:fd.get("street"),number:fd.get("number"),complement:fd.get("complement")||null,district:fd.get("district"),city:fd.get("city"),state:String(fd.get("state")||"").toUpperCase(),isDefault:fd.get("isDefault")==="on"};const hasId="id" in (editing as any);const r=await fetch(hasId?`/api/addresses/${(editing as Address).id}`:"/api/addresses",{method:hasId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error??"Falha ao salvar endereço.");return;}setEditing(null);router.refresh();}
async function remove(id:string){if(!confirm("Excluir este endereço?"))return;const r=await fetch(`/api/addresses/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setError(d.error??"Não foi possível excluir.");return;}router.refresh();}
return <div className="space-y-4"><div className="flex justify-end"><Button onClick={()=>setEditing({...empty})}><Plus className="size-4"/>Novo endereço</Button></div>{editing&&<Card className="p-5"><div className="mb-4 flex items-center justify-between"><strong>{"id" in (editing as any)?"Editar endereço":"Novo endereço"}</strong><Button variant="ghost" size="icon" onClick={()=>setEditing(null)}><X className="size-4"/></Button></div><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><F label="Apelido"><Input name="label" defaultValue={editing.label} required/></F><F label="Nome do recebedor"><Input name="recipient" defaultValue={editing.recipient??""}/></F><F label="CEP"><Input name="postalCode" defaultValue={editing.postalCode} inputMode="numeric" required/></F><F label="Rua / avenida"><Input name="street" defaultValue={editing.street} required/></F><F label="Número"><Input name="number" defaultValue={editing.number} required/></F><F label="Complemento"><Input name="complement" defaultValue={editing.complement??""}/></F><F label="Bairro"><Input name="district" defaultValue={editing.district} required/></F><F label="Cidade"><Input name="city" defaultValue={editing.city} required/></F><F label="UF"><Input name="state" defaultValue={editing.state} maxLength={2} required/></F><label className="flex items-center gap-2 self-end pb-2 text-sm"><input name="isDefault" type="checkbox" defaultChecked={editing.isDefault}/> Endereço padrão</label>{error&&<p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="sm:col-span-2 flex justify-end"><Button disabled={busy}>{busy?"Salvando...":"Salvar endereço"}</Button></div></form></Card>}
<div className="grid gap-3 md:grid-cols-2">{addresses.map(a=><Card key={a.id} className="p-4"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-blue-50 text-[var(--brand)]"><MapPin className="size-4"/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong>{a.label}</strong>{a.isDefault&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] text-slate-500">Padrão</span>}</div><p className="mt-1 text-sm text-slate-600">{a.street}, {a.number}{a.complement?` · ${a.complement}`:""} · {a.district}</p><p className="text-xs text-slate-500">{a.city}/{a.state} · CEP {a.postalCode}</p><div className="mt-3 flex gap-2"><Button variant="outline" size="sm" onClick={()=>setEditing(a)}><Pencil className="size-3.5"/>Editar</Button><Button variant="ghost" size="sm" onClick={()=>remove(a.id)}><Trash2 className="size-3.5"/>Excluir</Button></div></div></div></Card>)}</div>{addresses.length===0&&!editing&&<Card className="p-8 text-center text-sm text-slate-500">Cadastre seu primeiro endereço para agendar uma coleta.</Card>}</div>}
function F({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
