"use client";
import Script from "next/script";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, CreditCard, Minus, Plus, QrCode, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { money } from "@/lib/utils";

type Service={id:string;name:string;description?:string|null;unit:string;price:number;estimatedHours:number};
type Address={id:string;label:string;street:string;number:string;district:string;city:string;state:string;postalCode:string};
type Slot={id:string;weekday:number;startTime:string;endTime:string;intervalMin:number;capacity:number;active:boolean};
type PaymentMethod="PIX"|"CREDIT_CARD"|"DEBIT_CARD";
type Quote={subtotal:number;discount:number;collectionFee:number;deliveryFee:number;total:number};
const inputClass="h-10 w-full rounded-[var(--radius)] border bg-white px-3 text-sm";
function pad(n:number){return String(n).padStart(2,"0")}
function localInput(d:Date){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function buildSchedule(slots:Slot[]){const out:{value:string;label:string}[]=[];const min=Date.now()+15*60*1000;for(let day=0;day<14;day++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+day);for(const slot of slots.filter(s=>s.weekday===d.getDay())){const[startH,startM]=slot.startTime.split(":").map(Number);const[endH,endM]=slot.endTime.split(":").map(Number);for(let m=startH*60+startM;m<endH*60+endM;m+=slot.intervalMin){const dt=new Date(d);dt.setHours(Math.floor(m/60),m%60,0,0);if(dt.getTime()<min)continue;out.push({value:localInput(dt),label:`${new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"}).format(dt)} · ${pad(dt.getHours())}:${pad(dt.getMinutes())}`})}}}return out}

export function CheckoutForm({services,addresses,lockers,user,slots,paymentOptions,defaultDeliveryHours}:{services:Service[];addresses:Address[];lockers:any[];user:{name?:string|null;email?:string|null;phone?:string|null};slots:Slot[];paymentOptions:{pix:boolean;credit:boolean;debit:boolean};defaultDeliveryHours:number}){
 const router=useRouter();const schedule=useMemo(()=>buildSchedule(slots),[slots]);
 const firstPayment:PaymentMethod=paymentOptions.pix?"PIX":paymentOptions.credit?"CREDIT_CARD":"DEBIT_CARD";
 const[qty,setQty]=useState<Record<string,number>>({});const[payment,setPayment]=useState<PaymentMethod>(firstPayment);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const[addressId,setAddressId]=useState(addresses[0]?.id??"");const[deliveryAddressId,setDeliveryAddressId]=useState(addresses[0]?.id??"");const[lockerId,setLockerId]=useState("");const[collectionAt,setCollectionAt]=useState(schedule[0]?.value??"");
 const initialDelivery=collectionAt?localInput(new Date(new Date(collectionAt).getTime()+defaultDeliveryHours*3600000)):"";const[deliveryAt,setDeliveryAt]=useState(initialDelivery);const[couponCode,setCouponCode]=useState("");const[quote,setQuote]=useState<Quote|null>(null);const[quoteError,setQuoteError]=useState("");
 const selectedAddress=addresses.find(a=>a.id===addressId);const selectedDeliveryAddress=addresses.find(a=>a.id===deliveryAddressId)??selectedAddress;
 const items=useMemo(()=>services.filter(s=>(qty[s.id]??0)>0).map(s=>({serviceId:s.id,quantity:qty[s.id]})),[services,qty]);
 const localSubtotal=useMemo(()=>services.reduce((a,s)=>a+(qty[s.id]??0)*s.price,0),[services,qty]);
 const paymentChoices=([paymentOptions.pix&&["PIX",QrCode,"PIX"],paymentOptions.credit&&["CREDIT_CARD",CreditCard,"Crédito"],paymentOptions.debit&&["DEBIT_CARD",CreditCard,"Débito 3DS"]].filter(Boolean)) as [PaymentMethod,any,string][];
 function changeCollection(value:string){setCollectionAt(value);if(value){const d=new Date(value);d.setHours(d.getHours()+defaultDeliveryHours);setDeliveryAt(localInput(d))}}
 async function requestQuote(){if(!addressId||items.length===0)return null;const res=await fetch("/api/orders/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({addressId,deliveryAddressId,couponCode,items})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Não foi possível calcular o pedido.");return data as Quote}
 useEffect(()=>{if(!addressId||items.length===0){setQuote(null);setQuoteError("");return}let active=true;const timer=setTimeout(async()=>{try{const q=await requestQuote();if(active){setQuote(q);setQuoteError("")}}catch(e:any){if(active){setQuote(null);setQuoteError(e.message??"Não foi possível calcular o pedido.")}}},350);return()=>{active=false;clearTimeout(timer)}},[addressId,deliveryAddressId,couponCode,items]);
 async function encryptCard(form:HTMLFormElement){const fd=new FormData(form);const PagSeguro=(window as any).PagSeguro;if(!PagSeguro)throw new Error("SDK do PagBank ainda não carregou.");if(!process.env.NEXT_PUBLIC_PAGBANK_PUBLIC_KEY)throw new Error("Chave pública do PagBank não configurada.");const card=PagSeguro.encryptCard({publicKey:process.env.NEXT_PUBLIC_PAGBANK_PUBLIC_KEY,holder:String(fd.get("holderName")||""),number:String(fd.get("cardNumber")||"").replace(/\D/g,""),expMonth:String(fd.get("expMonth")||""),expYear:String(fd.get("expYear")||""),securityCode:String(fd.get("cvv")||"")});if(card.hasErrors)throw new Error(card.errors?.[0]?.message??"Confira os dados do cartão.");return card.encryptedCard as string}
 async function authenticateDebit(encryptedCard:string,amount:number){const PagSeguro=(window as any).PagSeguro;if(!PagSeguro)throw new Error("SDK do PagBank indisponível.");const sessionRes=await fetch("/api/pagbank/3ds-session",{method:"POST"});const session=await sessionRes.json();if(!sessionRes.ok)throw new Error(session.error||"Falha ao iniciar 3DS.");PagSeguro.setUp({session:session.session,env:session.env});const phone=String(user.phone??"").replace(/\D/g,"").replace(/^55/,"");if(phone.length<10)throw new Error("Atualize seu telefone antes de pagar com débito.");const result=await PagSeguro.authenticate3DS({data:{customer:{name:user.name,email:user.email,phones:[{country:"55",area:phone.slice(0,2),number:phone.slice(2),type:"MOBILE"}]},paymentMethod:{type:"DEBIT_CARD",installments:1,card:{encrypted:encryptedCard}},amount:{value:Math.round(amount*100),currency:"BRL"},billingAddress:{street:selectedAddress?.street,number:selectedAddress?.number,city:selectedAddress?.city,regionCode:selectedAddress?.state,country:"BRA",postalCode:selectedAddress?.postalCode.replace(/\D/g,"")},shippingAddress:{street:selectedDeliveryAddress?.street,number:selectedDeliveryAddress?.number,city:selectedDeliveryAddress?.city,regionCode:selectedDeliveryAddress?.state,country:"BRA",postalCode:selectedDeliveryAddress?.postalCode.replace(/\D/g,"")},dataOnly:false}});if(result.status!=="AUTH_FLOW_COMPLETED")throw new Error(result.status==="AUTH_NOT_SUPPORTED"?"Este cartão não permite débito online com 3DS.":"Não foi possível autenticar o cartão.");return result.id as string}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(localSubtotal<=0){setError("Selecione pelo menos um serviço.");return}if(!addressId){setError("Cadastre um endereço antes de continuar.");return}if(!collectionAt){setError("Não há horário de coleta selecionado.");return}setLoading(true);try{const exactQuote=await requestQuote();if(!exactQuote)throw new Error("Não foi possível calcular o pedido.");setQuote(exactQuote);const form=e.currentTarget;const fd=new FormData(form);let encryptedCard:string|undefined;let threeDSId:string|undefined;if(payment!=="PIX"&&exactQuote.total>0){encryptedCard=await encryptCard(form);if(payment==="DEBIT_CARD")threeDSId=await authenticateDebit(encryptedCard,exactQuote.total)}const res=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({addressId,deliveryAddressId,collectionAt,deliveryExpectedAt:deliveryAt,notes:fd.get("notes"),couponCode,paymentMethod:payment,lockerId:lockerId||undefined,encryptedCard,threeDSId,holderName:fd.get("holderName"),holderTaxId:fd.get("holderTaxId"),installments:Number(fd.get("installments")||1),items})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Não foi possível concluir o pedido.");sessionStorage.setItem(`payment:${data.orderId}`,JSON.stringify(data.payment));router.push(`/app/pedidos/${data.orderId}`);router.refresh()}catch(err:any){setError(err.message??"Falha ao concluir.");setLoading(false)}}
 const shown:Quote=quote??{subtotal:localSubtotal,discount:0,collectionFee:0,deliveryFee:0,total:localSubtotal};
 return <><Script src="https://assets.pagseguro.com.br/checkout-sdk-js/rc/dist/browser/pagseguro.min.js" strategy="afterInteractive"/><form onSubmit={submit} className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5">
 <Card><CardHeader><CardTitle>1. Escolha os serviços</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{services.map(s=><div key={s.id} className={`rounded-xl border p-4 ${(qty[s.id]??0)>0?"border-blue-200 bg-blue-50/40":""}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{s.name}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{s.description}</p><div className="mt-2 text-sm font-semibold text-[var(--brand)]">{money(s.price)} <span className="text-[10px] font-medium text-slate-400">/{s.unit==="KG"?"kg":"un."}</span></div></div><div className="flex items-center gap-2"><Button type="button" variant="outline" size="icon" className="size-8" onClick={()=>setQty(q=>({...q,[s.id]:Math.max(0,(q[s.id]??0)-1)}))}><Minus className="size-3"/></Button><span className="w-5 text-center text-sm font-semibold">{qty[s.id]??0}</span><Button type="button" variant="outline" size="icon" className="size-8" onClick={()=>setQty(q=>({...q,[s.id]:(q[s.id]??0)+1}))}><Plus className="size-3"/></Button></div></div></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>2. Coleta e entrega</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Endereço de coleta</Label><select value={addressId} onChange={e=>setAddressId(e.target.value)} className={inputClass}>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} — {a.street}, {a.number}</option>)}</select></div><div className="space-y-1.5"><Label>Endereço de entrega</Label><select value={deliveryAddressId} onChange={e=>setDeliveryAddressId(e.target.value)} className={inputClass}>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} — {a.street}, {a.number}</option>)}</select></div><div className="space-y-1.5 sm:col-span-2"><Label>Uso de armário (opcional)</Label><select value={lockerId} onChange={e=>setLockerId(e.target.value)} className={inputClass}><option value="">Sem armário — coleta no endereço</option>{lockers.map((l:any)=><option key={l.id} value={l.id}>{l.name} · {l.locationName} · {l.compartment??""}</option>)}</select>{lockerId&&<p className="text-[10px] text-slate-500">Após o pagamento, o armário é autorizado somente na janela do horário escolhido.</p>}</div><div className="space-y-1.5"><Label>Data e horário da coleta</Label><select value={collectionAt} onChange={e=>changeCollection(e.target.value)} className={inputClass} required><option value="">Selecione</option>{schedule.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select>{schedule.length===0&&<p className="text-[10px] text-red-600">Sem horários ativos nos próximos 14 dias.</p>}</div><div className="space-y-1.5"><Label>Previsão de entrega</Label><Input name="deliveryExpectedAt" type="datetime-local" value={deliveryAt} onChange={e=>setDeliveryAt(e.target.value)} required/></div><div className="space-y-1.5 sm:col-span-2"><Label>Observações</Label><Textarea name="notes" placeholder="Ex.: interfone 22, peça delicada, preferência de contato..."/></div></CardContent></Card>
 <Card><CardHeader><CardTitle>3. Pagamento</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-3">{paymentChoices.map(([id,Icon,label])=><button type="button" key={id} onClick={()=>setPayment(id)} className={`flex h-12 items-center justify-center gap-2 rounded-lg border text-sm font-semibold ${payment===id?"border-[var(--brand)] bg-blue-50 text-[var(--brand)]":"bg-white"}`}><Icon className="size-4"/>{label}{payment===id&&<Check className="size-3.5"/>}</button>)}</div>{payment!=="PIX"&&shown.total>0&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="space-y-1.5 sm:col-span-2"><Label>Número do cartão</Label><Input name="cardNumber" inputMode="numeric" autoComplete="cc-number" required/></div><div className="space-y-1.5 sm:col-span-2"><Label>Nome no cartão</Label><Input name="holderName" autoComplete="cc-name" required/></div><div className="space-y-1.5"><Label>CPF do titular</Label><Input name="holderTaxId" inputMode="numeric" required/></div><div className="grid grid-cols-3 gap-2"><div className="space-y-1.5"><Label>Mês</Label><Input name="expMonth" placeholder="MM" required/></div><div className="space-y-1.5"><Label>Ano</Label><Input name="expYear" placeholder="AAAA" required/></div><div className="space-y-1.5"><Label>CVV</Label><Input name="cvv" type="password" required/></div></div>{payment==="CREDIT_CARD"&&<div className="space-y-1.5"><Label>Parcelas</Label><select name="installments" className={inputClass}>{[1,2,3,4,5,6,7,8,9,10,11,12].map(n=><option key={n} value={n}>{n}x</option>)}</select></div>}<div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="size-4 text-emerald-600"/> Dados criptografados pelo SDK do PagBank.</div></div>}</CardContent></Card>
 </div><aside className="lg:sticky lg:top-5 lg:self-start"><Card><CardHeader><CardTitle>Resumo do pedido</CardTitle></CardHeader><CardContent className="space-y-3"><div className="space-y-2">{services.filter(s=>(qty[s.id]??0)>0).map(s=><div key={s.id} className="flex justify-between gap-3 text-xs"><span className="text-slate-600">{qty[s.id]}× {s.name}</span><strong>{money((qty[s.id]??0)*s.price)}</strong></div>)}</div><div className="border-t pt-3 text-xs"><div className="flex justify-between py-1"><span className="text-slate-500">Subtotal</span><span>{money(shown.subtotal)}</span></div><div className="flex justify-between py-1"><span className="text-slate-500">Taxa de coleta</span><span>{money(shown.collectionFee)}</span></div><div className="flex justify-between py-1"><span className="text-slate-500">Taxa de entrega</span><span>{money(shown.deliveryFee)}</span></div>{shown.discount>0&&<div className="flex justify-between py-1 text-emerald-700"><span>Desconto</span><span>− {money(shown.discount)}</span></div>}</div><div className="space-y-1.5"><Label>Cupom</Label><Input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} placeholder="BEMVINDO10"/></div><div className="flex items-end justify-between border-t pt-4"><span className="text-sm font-semibold">Total</span><strong className="text-2xl tracking-tight">{money(shown.total)}</strong></div>{quoteError&&items.length>0&&<p className="rounded-lg bg-amber-50 p-3 text-xs font-medium text-amber-800">{quoteError}</p>}{error&&<p className="rounded-lg bg-red-50 p-3 text-xs font-medium text-red-700">{error}</p>}<Button className="w-full" size="lg" disabled={loading||schedule.length===0||paymentChoices.length===0}>{loading?"Processando...":"Confirmar e pagar"}</Button></CardContent></Card></aside></form></>
}
