"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { money } from "@/lib/utils";
import { Pencil, Power, Plus, X } from "lucide-react";

export function ServiceManager({services}:{services:any[]}){
 const r=useRouter();const[busy,setBusy]=useState(false);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<any|null>(null);const[error,setError]=useState("");
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const res=await fetch("/api/admin/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});const d=await res.json();setBusy(false);if(!res.ok){setError(d.error??"Falha ao salvar");return}setOpen(false);r.refresh();}
 async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const body={name:fd.get("name"),description:fd.get("description"),unit:fd.get("unit"),price:Number(fd.get("price")),estimatedHours:Number(fd.get("estimatedHours"))};const res=await fetch(`/api/admin/services/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await res.json();setBusy(false);if(!res.ok){setError(d.error??"Falha ao atualizar");return}setEditing(null);r.refresh();}
 async function toggle(id:string,active:boolean){await fetch(`/api/admin/services/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:!active})});r.refresh();}
 const form=(initial:any,submit:any)=><form onSubmit={submit} className="grid gap-4 md:grid-cols-5"><div className="space-y-1.5 md:col-span-2"><Label>Nome</Label><Input name="name" defaultValue={initial?.name??""} required/></div><div className="space-y-1.5"><Label>Unidade</Label><select name="unit" defaultValue={initial?.unit??"ITEM"} className="h-10 w-full rounded-md border bg-white px-3"><option value="ITEM">Peça</option><option value="KG">Kg</option><option value="BAG">Volume</option><option value="SERVICE">Serviço</option></select></div><div className="space-y-1.5"><Label>Preço</Label><Input name="price" type="number" step="0.01" min="0.01" defaultValue={initial?Number(initial.price):""} required/></div><div className="space-y-1.5"><Label>Prazo (h)</Label><Input name="estimatedHours" type="number" min="1" defaultValue={initial?.estimatedHours??48} required/></div><div className="space-y-1.5 md:col-span-4"><Label>Descrição</Label><Input name="description" defaultValue={initial?.description??""}/></div><div className="flex items-end"><Button className="w-full" disabled={busy}>{busy?"Salvando...":"Salvar"}</Button></div>{error&&<p className="md:col-span-5 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}</form>;
 return <div className="space-y-4"><div className="flex justify-end"><Button onClick={()=>{setEditing(null);setOpen(v=>!v)}}><Plus className="size-4"/>Novo serviço</Button></div>{open&&<Card className="p-5">{form(null,create)}</Card>}{editing&&<Card className="p-5"><div className="mb-4 flex items-center justify-between"><strong>Editar serviço e preço</strong><Button variant="ghost" size="icon" onClick={()=>setEditing(null)}><X className="size-4"/></Button></div>{form(editing,update)}</Card>}<Card className="overflow-hidden"><div className="divide-y">{services.map(s=><div key={s.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong>{s.name}</strong><Badge variant={s.active?"success":"secondary"}>{s.active?"Ativo":"Inativo"}</Badge></div><p className="mt-1 text-xs text-slate-500">{s.description||"Sem descrição"} · {s.estimatedHours}h</p></div><div className="text-sm font-semibold">{money(Number(s.price))} / {s.unit}</div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>{setOpen(false);setEditing(s)}}><Pencil className="size-3.5"/>Editar</Button><Button variant="outline" size="sm" onClick={()=>toggle(s.id,s.active)}><Power className="size-3.5"/>{s.active?"Desativar":"Ativar"}</Button></div></div>)}</div></Card></div>
}
