"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Pencil, Plus, Power, X } from "lucide-react";

const perms=["orders.view","orders.edit","customers.view","staff.manage","services.manage","routes.manage","finance.view","settings.manage"];
const permissionLabels:Record<string,string>={
  "orders.view":"Ver pedidos","orders.edit":"Alterar pedidos","customers.view":"Ver clientes","staff.manage":"Gerenciar equipe",
  "services.manage":"Serviços e preços","routes.manage":"Rotas e agenda","finance.view":"Relatórios financeiros","settings.manage":"Configurações"
};
const roleLabels:Record<string,string>={ADMIN:"Administrador",MANAGER:"Gerente",ATTENDANT:"Atendimento",DRIVER:"Motorista",EMPLOYEE:"Funcionário"};

type Staff={id:string;name:string;email:string;phone?:string|null;role:string;status:string;permissions?:string[];staffProfile?:{vehicle?:string|null;plate?:string|null}|null};

function PermissionGrid({selected=[]}:{selected?:string[]}){return <div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{perms.map(p=><label key={p} className="flex items-center gap-2 rounded-lg border p-2.5 text-xs"><input name={p} type="checkbox" defaultChecked={selected.includes(p)||selected.includes("*")}/>{permissionLabels[p]}</label>)}</div>}

export function StaffManager({staff}:{staff:Staff[]}){
 const r=useRouter();const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Staff|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const permissions=perms.filter(p=>fd.get(p)==="on");const body={name:fd.get("name"),email:fd.get("email"),password:fd.get("password"),role:fd.get("role"),phone:fd.get("phone"),vehicle:fd.get("vehicle"),plate:fd.get("plate"),permissions};const res=await fetch("/api/admin/staff",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();setBusy(false);if(res.ok){setOpen(false);r.refresh();return}setError(data.error??"Não foi possível criar o acesso.");}
 async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError("");const fd=new FormData(e.currentTarget);const permissions=perms.filter(p=>fd.get(p)==="on");const body={name:fd.get("name"),email:fd.get("email"),role:fd.get("role"),phone:fd.get("phone"),vehicle:fd.get("vehicle"),plate:fd.get("plate"),permissions};const res=await fetch(`/api/admin/staff/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json();setBusy(false);if(res.ok){setEditing(null);r.refresh();return}setError(data.error??"Não foi possível salvar.");}
 async function toggle(id:string,status:string){const res=await fetch(`/api/admin/staff/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:status==="ACTIVE"?"DISABLED":"ACTIVE"})});if(!res.ok){const data=await res.json();setError(data.error??"Não foi possível alterar o acesso.");return}r.refresh();}
 return <div className="space-y-4">
  <div className="flex justify-end"><Button onClick={()=>{setOpen(v=>!v);setEditing(null);setError("")}}><Plus className="size-4"/>Novo funcionário</Button></div>
  {error&&<p className="rounded-lg bg-red-50 p-3 text-xs font-medium text-red-700">{error}</p>}
  {open&&<Card className="p-5"><div className="mb-4 flex items-center justify-between"><strong>Novo acesso</strong><Button type="button" variant="ghost" size="icon" onClick={()=>setOpen(false)}><X className="size-4"/></Button></div><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><div className="space-y-1.5"><Label>Nome</Label><Input name="name" required/></div><div className="space-y-1.5"><Label>E-mail</Label><Input name="email" type="email" required/></div><div className="space-y-1.5"><Label>Senha inicial</Label><Input name="password" type="password" required/></div><div className="space-y-1.5"><Label>Telefone</Label><Input name="phone"/></div><div className="space-y-1.5"><Label>Nível</Label><select name="role" className="h-10 w-full rounded-md border bg-white px-3">{Object.entries(roleLabels).filter(([k])=>k!=="ADMIN").map(([k,v])=><option key={k} value={k}>{v}</option>)}<option value="ADMIN">Administrador</option></select></div><div className="grid grid-cols-2 gap-2"><div className="space-y-1.5"><Label>Veículo</Label><Input name="vehicle"/></div><div className="space-y-1.5"><Label>Placa</Label><Input name="plate"/></div></div><div className="md:col-span-2"><Label>Permissões</Label><PermissionGrid/></div><div className="md:col-span-2 flex justify-end"><Button disabled={busy}>{busy?"Salvando...":"Criar acesso"}</Button></div></form></Card>}
  {editing&&<Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><strong>Editar acesso</strong><p className="mt-1 text-xs text-slate-500">{editing.name}</p></div><Button type="button" variant="ghost" size="icon" onClick={()=>setEditing(null)}><X className="size-4"/></Button></div><form key={editing.id} onSubmit={update} className="grid gap-4 md:grid-cols-2"><div className="space-y-1.5"><Label>Nome</Label><Input name="name" defaultValue={editing.name} required/></div><div className="space-y-1.5"><Label>E-mail</Label><Input name="email" type="email" defaultValue={editing.email} required/></div><div className="space-y-1.5"><Label>Telefone</Label><Input name="phone" defaultValue={editing.phone??""}/></div><div className="space-y-1.5"><Label>Nível</Label><select name="role" defaultValue={editing.role} className="h-10 w-full rounded-md border bg-white px-3">{Object.entries(roleLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="grid grid-cols-2 gap-2 md:col-span-2"><div className="space-y-1.5"><Label>Veículo</Label><Input name="vehicle" defaultValue={editing.staffProfile?.vehicle??""}/></div><div className="space-y-1.5"><Label>Placa</Label><Input name="plate" defaultValue={editing.staffProfile?.plate??""}/></div></div><div className="md:col-span-2"><Label>Permissões</Label><PermissionGrid selected={editing.permissions??[]}/></div><div className="md:col-span-2 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancelar</Button><Button disabled={busy}>{busy?"Salvando...":"Salvar alterações"}</Button></div></form></Card>}
  <Card className="divide-y">{staff.map(u=><div key={u.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{u.name}</strong><Badge>{roleLabels[u.role]??u.role}</Badge><Badge variant={u.status==="ACTIVE"?"success":"secondary"}>{u.status==="ACTIVE"?"Ativo":"Desativado"}</Badge></div><p className="mt-1 text-xs text-slate-500">{u.email}{u.staffProfile?.vehicle?` · ${u.staffProfile.vehicle} ${u.staffProfile.plate??""}`:""}</p><p className="mt-1 truncate text-[10px] text-slate-400">{(u.permissions??[]).map(p=>permissionLabels[p]??p).join(" · ")||"Sem permissões extras"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>{setEditing(u);setOpen(false);setError("")}}><Pencil className="size-3.5"/>Editar</Button><Button variant="outline" size="sm" onClick={()=>toggle(u.id,u.status)}><Power className="size-3.5"/>{u.status==="ACTIVE"?"Desativar":"Ativar"}</Button></div></div>)}</Card>
 </div>;
}
