import Link from "next/link";
import { CalendarClock, CircleDollarSign, ClipboardList, PackageCheck, ArrowRight, LockKeyhole } from "lucide-react";
import { auth } from "@/auth";
import { hasPermission } from "@/lib/access";
import { getDashboardStats } from "@/lib/admin-data";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/layout/status-badge";
import { money, dateTime } from "@/lib/utils";
export default async function Page(){const s=await auth();const canOrders=!!s?.user&&hasPermission(s.user,"orders.view");const canFinance=!!s?.user&&hasPermission(s.user,"finance.view");if(!canOrders&&!canFinance)return <div className="page-container"><PageHeader title="Visão geral" description="Seu acesso está ativo."/><Card className="max-w-xl p-8 text-center"><LockKeyhole className="mx-auto size-8 text-slate-400"/><h2 className="mt-3 font-semibold">Nenhum módulo operacional atribuído</h2><p className="mt-1 text-sm text-slate-500">Solicite ao administrador as permissões necessárias para acessar pedidos, clientes, rotas ou financeiro.</p></Card></div>;const d=await getDashboardStats();const cards:any[]=[];if(canOrders)cards.push([ClipboardList,"Pedidos hoje",d.ordersToday],[CalendarClock,"Em andamento",d.pending],[PackageCheck,"Entregas previstas",d.deliveriesToday]);if(canFinance)cards.push([CircleDollarSign,"Recebido hoje",money(d.revenueToday)]);return <div className="page-container"><PageHeader title="Visão geral" description="Operação da lavanderia em tempo real." action={canOrders?<Button asChild><Link href="/admin/pedidos">Abrir pedidos <ArrowRight className="size-4"/></Link></Button>:undefined}/><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon,label,value]:any)=><Card key={label}><CardContent className="p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><Icon className="size-4 text-[var(--brand)]"/></div><div className="metric-value mt-2">{value}</div></CardContent></Card>)}</div><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]">{canOrders&&<Card><CardHeader><CardTitle>Pedidos recentes</CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y">{d.recent.map((o:any)=><Link key={o.id} href="/admin/pedidos" className="flex items-center gap-3 px-5 py-3 hover:bg-slate-50"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="text-sm">{o.number}</strong><StatusBadge status={o.status}/></div><p className="mt-1 truncate text-xs text-slate-500">{o.customer?.name} · entrega {dateTime(o.deliveryExpectedAt)}</p></div>{canFinance&&<strong className="text-sm">{money(o.total)}</strong>}</Link>)}</div></CardContent></Card>}<div className="space-y-5">{canOrders&&<Card><CardHeader><CardTitle>Pedidos por status</CardTitle></CardHeader><CardContent className="space-y-3">{d.byStatus.map((x:any)=><div key={x.status} className="flex items-center justify-between text-xs"><StatusBadge status={x.status}/><strong>{x.count}</strong></div>)}</CardContent></Card>}{canFinance&&<Card><CardHeader><CardTitle>Pagamentos</CardTitle></CardHeader><CardContent className="space-y-3">{d.payments.map((x:any)=><div key={x.status} className="flex justify-between text-xs"><span className="text-slate-500">{x.status}</span><strong>{money(x.amount)}</strong></div>)}</CardContent></Card>}</div></div></div>}
