import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarClock, CircleDollarSign, ClipboardList, Clock3, PackageCheck, Route, Truck, WalletCards } from "lucide-react";
import { auth } from "@/auth";import { hasPermission } from "@/lib/access";import { getDashboardStats } from "@/lib/admin-data";import { PageHeader } from "@/components/layout/page-header";import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";import { Button } from "@/components/ui/button";import { StatusBadge } from "@/components/layout/status-badge";import { money, dateTime } from "@/lib/utils";
const tone:any={danger:"border-red-200 bg-red-50 text-red-800",warning:"border-amber-200 bg-amber-50 text-amber-900",info:"border-blue-200 bg-blue-50 text-blue-800"};
export default async function Page(){const s=await auth();const canOrders=!!s?.user&&hasPermission(s.user,"orders.view");const canFinance=!!s?.user&&hasPermission(s.user,"finance.view");const d:any=await getDashboardStats();
 const cards=[[ClipboardList,"Pedidos hoje",d.ordersToday,"+12% vs. média"],[Clock3,"Em andamento",d.pending,"na operação"],[CalendarClock,"Coletas hoje",d.collectionsToday,"agenda do dia"],[PackageCheck,"Entregas hoje",d.deliveriesToday,"previstas"],[CircleDollarSign,"Recebido hoje",money(d.revenueToday),"pagamentos pagos"],[WalletCards,"A receber",money(d.pendingPayment),"pendente/análise"],[CircleDollarSign,"Ticket médio",money(d.avgTicket),"pedidos de hoje"],[AlertTriangle,"Atenção",d.delayed,d.delayed===1?"entrega no limite":"entregas no limite"]];
 const max=Math.max(...d.revenueWeek.map((x:any)=>x.v),1);
 return <div className="page-container"><PageHeader title="Visão geral" description="Operação, financeiro e logística em tempo real." action={<div className="flex gap-2"><Button asChild variant="outline"><Link href="/admin/relatorios">Ver relatórios</Link></Button>{canOrders&&<Button asChild><Link href="/admin/pedidos">Abrir pedidos <ArrowRight className="size-4"/></Link></Button>}</div>}/>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.filter((_:any,i:number)=>canFinance||![4,5,6].includes(i)).map(([Icon,label,value,hint]:any)=><Card key={label}><CardContent className="p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><Icon className="size-4 text-[var(--brand)]"/></div><div className="metric-value mt-2">{value}</div><div className="mt-1 text-[10px] text-slate-400">{hint}</div></CardContent></Card>)}</div>
 <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
  <div className="space-y-5"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Agenda de hoje</CardTitle><Link href="/admin/agenda" className="text-xs font-semibold text-[var(--brand)]">Abrir agenda</Link></CardHeader><CardContent className="p-0"><div className="divide-y">{d.todayAgenda.map((o:any)=>{const isCollection=new Date(o.collectionAt).toDateString()===new Date("2026-08-11T12:00:00-03:00").toDateString();return <Link key={o.id} href={`/admin/pedidos/${o.id}`} className="grid gap-3 px-5 py-3 hover:bg-slate-50 sm:grid-cols-[72px_1fr_auto] sm:items-center"><div className="text-xs font-bold text-slate-700">{new Date(isCollection?o.collectionAt:o.deliveryExpectedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</div><div><strong className="text-sm">{isCollection?"Coleta":"Entrega"} · {o.customer?.name}</strong><p className="mt-0.5 text-[11px] text-slate-500">{o.number}</p></div><StatusBadge status={o.status}/></Link>})}</div></CardContent></Card>
  <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Pedidos recentes</CardTitle><Link href="/admin/pedidos" className="text-xs font-semibold text-[var(--brand)]">Ver todos</Link></CardHeader><CardContent className="p-0"><div className="divide-y">{d.recent.map((o:any)=><Link key={o.id} href={`/admin/pedidos/${o.id}`} className="flex items-center gap-3 px-5 py-3 hover:bg-slate-50"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="text-sm">{o.number}</strong><StatusBadge status={o.status}/></div><p className="mt-1 truncate text-xs text-slate-500">{o.customer?.name} · entrega {dateTime(o.deliveryExpectedAt)}</p></div>{canFinance&&<strong className="text-sm">{money(o.total)}</strong>}</Link>)}</div></CardContent></Card></div>
  <div className="space-y-5"><Card><CardHeader><CardTitle>Alertas operacionais</CardTitle></CardHeader><CardContent className="space-y-2">{d.alerts.length?d.alerts.map((a:any)=><div key={a.title} className={`rounded-lg border p-3 text-xs ${tone[a.tone]??tone.info}`}><strong>{a.title}</strong><p className="mt-1 opacity-80">{a.text}</p></div>):<div className="rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700"><strong>Operação normal</strong><p className="mt-1">Nenhum alerta crítico.</p></div>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Equipe em rota</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-3"><Truck className="size-4 text-[var(--brand)]"/><div className="mt-2 text-xl font-bold">{d.activeDrivers}</div><div className="text-[10px] text-slate-500">motoristas ativos</div></div><div className="rounded-lg bg-slate-50 p-3"><Route className="size-4 text-[var(--brand)]"/><div className="mt-2 text-xl font-bold">{d.openRoutes}</div><div className="text-[10px] text-slate-500">rotas abertas</div></div></div><Button asChild variant="outline" size="sm" className="mt-3 w-full"><Link href="/admin/rotas">Gerenciar rotas</Link></Button></CardContent></Card>
  <Card><CardHeader><CardTitle>Pagamentos</CardTitle></CardHeader><CardContent className="space-y-3">{d.payments.map((x:any)=><div key={x.status} className="flex justify-between text-xs"><span className="text-slate-500">{x.status}</span><strong>{money(x.amount)}</strong></div>)}</CardContent></Card></div>
 </div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr_.8fr]"><Card><CardHeader><CardTitle>Receita nos últimos 7 dias</CardTitle></CardHeader><CardContent><div className="flex h-40 items-end gap-3">{d.revenueWeek.map((x:any)=><div key={x.d} className="flex h-full flex-1 flex-col justify-end"><div className="rounded-t bg-[var(--brand)]/85" style={{height:`${Math.max(8,(x.v/max)*120)}px`}}/><div className="mt-2 text-center text-[10px] text-slate-500">{x.d}</div></div>)}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>Serviços mais vendidos</CardTitle></CardHeader><CardContent className="space-y-3">{(d.topServices.length?d.topServices:[{name:"Sem dados ainda",orders:0,revenue:0}]).map((x:any,i:number)=><div key={x.name} className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-md bg-blue-50 text-[11px] font-bold text-[var(--brand)]">{i+1}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{x.name}</div><div className="text-[10px] text-slate-400">{x.orders} pedidos</div></div><strong className="text-xs">{money(x.revenue)}</strong></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Atividade recente</CardTitle></CardHeader><CardContent className="space-y-4">{d.activity.map((x:any)=><div key={x.action+x.when} className="text-xs"><strong>{x.actor}</strong><p className="mt-0.5 text-slate-500">{x.action}</p><span className="text-[10px] text-slate-400">{x.when}</span></div>)}</CardContent></Card></div>
 </div>}
